// The Source of Truth
// Generated by Visual Editor

const FAMILY_DATA = [
    {
        "id": "alice",
        "name": "Alice Schüpbach",
        "ledigname": "Scheurer",
        "birthDate": "1937",
        "deathDate": "2025",
        "generation": 1,
        "partners": [
            "werner"
        ],
        "photo": null,
        "x": 570,
        "y": 200
    },
    {
        "id": "id_17668782344693rje",
        "name": "Bertha Schüpbach",
        "ledigname": "Bieri",
        "birthDate": "",
        "generation": 1,
        "partners": [
            "id_17668781750526pgb"
        ],
        "photo": null,
        "x": 358,
        "y": 18
    },
    {
        "id": "id_17668789424930yol",
        "name": "Ernst Otto Marti",
        "birthDate": "1903",
        "deathDate": "1979",
        "generation": 1,
        "photo": null,
        "x": 826,
        "y": -24
    },
    {
        "id": "roland",
        "name": "Roland Herzig",
        "birthDate": "",
        "generation": 1,
        "partners": [
            "barbara"
        ],
        "photo": null,
        "x": 167,
        "y": 401
    },
    {
        "id": "sonja",
        "name": "Sonja Klara Marti",
        "ledigname": "Gysi",
        "birthDate": "1933",
        "generation": 1,
        "partners": [
            "wolfgang"
        ],
        "photo": null,
        "x": 1074,
        "y": 170
    },
    {
        "id": "valentina",
        "name": "Valentina Melillo",
        "birthDate": "1996",
        "generation": 1,
        "partners": [
            "nick"
        ],
        "photo": null,
        "x": 1166,
        "y": 634
    },
    {
        "id": "id_1766878449340i6dc",
        "name": "Walter Caviezel",
        "birthDate": "",
        "generation": 1,
        "partners": [
            "cristina"
        ],
        "photo": null,
        "x": 1384,
        "y": 400
    },
    {
        "id": "id_17668781750526pgb",
        "name": "Walter Schüpbach",
        "birthDate": "",
        "generation": 1,
        "partners": [
            "id_17668782344693rje"
        ],
        "photo": null,
        "x": 147,
        "y": 17
    },
    {
        "id": "wolfgang",
        "name": "Ernst Wolfgang Marti",
        "birthDate": "1928",
        "deathDate": "2019",
        "generation": 2,
        "parents": [
            "id_17668789424930yol"
        ],
        "partners": [
            "sonja"
        ],
        "photo": null,
        "x": 877,
        "y": 172
    },
    {
        "id": "id_1766878323637mb2g",
        "name": "Jolanda Schüpbach",
        "birthDate": "",
        "generation": 2,
        "parents": [
            "id_17668781750526pgb",
            "id_17668782344693rje"
        ],
        "photo": null,
        "x": -54,
        "y": 193
    },
    {
        "id": "id_1766878209454vbyr",
        "name": "Walter Schüpbach Jr. ",
        "birthDate": "",
        "generation": 2,
        "parents": [
            "id_17668781750526pgb",
            "id_17668782344693rje"
        ],
        "photo": null,
        "x": 143,
        "y": 193
    },
    {
        "id": "werner",
        "name": "Werner Schüpbach",
        "birthDate": "1937",
        "deathDate": "2025",
        "generation": 2,
        "parents": [
            "id_17668781750526pgb",
            "id_17668782344693rje"
        ],
        "partners": [
            "alice"
        ],
        "photo": null,
        "x": 337,
        "y": 192
    },
    {
        "id": "adrian",
        "name": "Adrian Schüpbach",
        "birthDate": "27.10.1964",
        "generation": 3,
        "parents": [
            "werner",
            "alice"
        ],
        "partners": [
            "claudia"
        ],
        "photo": "images/adrian.jpg",
        "x": 645,
        "y": 398
    },
    {
        "id": "barbara",
        "name": "Barbara Schüpbach",
        "birthDate": "1962",
        "deathDate": "2008",
        "generation": 3,
        "parents": [
            "werner",
            "alice"
        ],
        "partners": [
            "roland"
        ],
        "photo": null,
        "x": 436,
        "y": 400
    },
    {
        "id": "claudia",
        "name": "Claudia Schüpbach",
        "ledigname": "Marti",
        "birthDate": "27.08.1965",
        "generation": 3,
        "parents": [
            "wolfgang",
            "sonja"
        ],
        "partners": [
            "adrian"
        ],
        "photo": "images/claudia.jpg",
        "x": 826,
        "y": 397
    },
    {
        "id": "corinna",
        "name": "Corinna Marti",
        "birthDate": "1968",
        "generation": 3,
        "parents": [
            "wolfgang",
            "sonja"
        ],
        "photo": null,
        "x": 1029,
        "y": 395
    },
    {
        "id": "cristina",
        "name": "Cristina Marti-Caviezel",
        "ledigname": "Marti",
        "birthDate": "1969",
        "generation": 3,
        "parents": [
            "wolfgang",
            "sonja"
        ],
        "partners": [
            "id_1766878449340i6dc"
        ],
        "photo": null,
        "x": 1201,
        "y": 393
    },
    {
        "id": "nick",
        "name": "Nick Schüpbach",
        "birthDate": "15.03.1995",
        "generation": 4,
        "parents": [
            "adrian",
            "claudia"
        ],
        "partners": [
            "valentina"
        ],
        "photo": "images/nick.jpg",
        "x": 971,
        "y": 636
    },
    {
        "id": "nino",
        "name": "Nino Herzig",
        "birthDate": "",
        "generation": 4,
        "parents": [
            "barbara",
            "roland"
        ],
        "photo": null,
        "x": 276,
        "y": 600
    },
    {
        "id": "noemi",
        "name": "Noemi Herzig",
        "birthDate": "",
        "generation": 4,
        "parents": [
            "barbara",
            "roland"
        ],
        "photo": null,
        "x": 495,
        "y": 600
    },
    {
        "id": "sven",
        "name": "Sven Schüpbach",
        "birthDate": "04.02.1993",
        "generation": 4,
        "parents": [
            "adrian",
            "claudia"
        ],
        "photo": "images/sven.jpg",
        "x": 790,
        "y": 638
    }
];